# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-19 03:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='users',
        ),
    ]
