# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0002_auto_20180418_2040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='f_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='l_name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
    ]
