# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg_app', '0003_auto_20180420_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('s_date', models.DateField()),
                ('e_date', models.DateField()),
                ('joiners', models.ManyToManyField(related_name='joining', to='login_reg_app.users')),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned', to='login_reg_app.users')),
            ],
        ),
    ]
